function Invoke-MTRReadinessCheck {
    <#
    .SYNOPSIS
        Runs all Teams Rooms readiness checks (calendar + network) and outputs results.
    .DESCRIPTION
        Orchestrates Exchange Online calendar-processing checks and local network
        connectivity checks. Results can be exported as JSON for upload to the
        web dashboard or as a standalone HTML report.
    .PARAMETER RoomMailboxes
        One or more UPNs or email addresses of room mailboxes to check.
        If omitted, only network checks are run.
    .PARAMETER SkipNetwork
        Skip network connectivity checks.
    .PARAMETER SkipCalendar
        Skip Exchange Online calendar processing checks.
    .PARAMETER OutputPath
        Path to save JSON results. If omitted, results are auto-saved to ./mtr-results.json.
    .PARAMETER AutoUpload
        URL to automatically upload results to. Generated by the web dashboard.
        Example: http://localhost:3000/api/upload?token=abc123
    .PARAMETER PassThru
        Return results as objects even when OutputPath is specified.
    .EXAMPLE
        Invoke-MTRReadinessCheck -RoomMailboxes 'mtr-room1@contoso.com','mtr-room2@contoso.com'
    .EXAMPLE
        Invoke-MTRReadinessCheck -RoomMailboxes 'mtr-room1@contoso.com' -AutoUpload 'http://localhost:3000/api/upload?token=abc123'
    .EXAMPLE
        Invoke-MTRReadinessCheck -SkipCalendar
    #>
    [CmdletBinding()]
    param(
        [Parameter(ValueFromPipeline, ValueFromPipelineByPropertyName)]
        [string[]]$RoomMailboxes,

        [switch]$SkipNetwork,
        [switch]$SkipCalendar,

        [string]$OutputPath,
        [string]$AutoUpload,
        [switch]$PassThru
    )

    begin {
        $allResults = [System.Collections.Generic.List[object]]::new()
        $hostname = if ($env:COMPUTERNAME) { $env:COMPUTERNAME } else { hostname }
    }

    process {
        # ---------------------------------------------------------------
        # Calendar checks (require Exchange Online connection)
        # ---------------------------------------------------------------
        if (-not $SkipCalendar -and $RoomMailboxes) {
            # Verify Exchange Online connection
            $exoConnected = $false
            try {
                $null = Get-Command Get-CalendarProcessing -ErrorAction Stop
                $exoConnected = $true
            }
            catch {
                Write-Warning "Exchange Online module not connected. Run Connect-ExchangeOnline first. Skipping calendar checks."
            }

            if ($exoConnected) {
                foreach ($mailbox in $RoomMailboxes) {
                    Write-Host "  Checking calendar processing: $mailbox" -ForegroundColor Cyan

                    $calResults = Test-CalendarProcessing -Identity $mailbox
                    foreach ($r in $calResults) { $allResults.Add($r) }

                    $extResult = Test-ExternalMeetingProcessing -Identity $mailbox
                    $allResults.Add($extResult)
                }
            }
        }
    }

    end {
        # ---------------------------------------------------------------
        # Network checks (local execution)
        # ---------------------------------------------------------------
        if (-not $SkipNetwork) {
            Write-Host "  Checking UDP port reachability (3478-3481)..." -ForegroundColor Cyan
            $allResults.Add((Test-UDPPortReachability))

            Write-Host "  Checking TCP 443 connectivity..." -ForegroundColor Cyan
            $allResults.Add((Test-TCPConnectivity))

            Write-Host "  Checking proxy authentication..." -ForegroundColor Cyan
            $allResults.Add((Test-ProxyAuthentication))

            Write-Host "  Checking TLS inspection..." -ForegroundColor Cyan
            $allResults.Add((Test-TLSInspection))

            Write-Host "  Checking WebSocket support..." -ForegroundColor Cyan
            $allResults.Add((Test-WebSocketSupport))

            Write-Host "  Estimating bandwidth..." -ForegroundColor Cyan
            $allResults.Add((Test-BandwidthAdequacy))
        }

        # ---------------------------------------------------------------
        # Summary
        # ---------------------------------------------------------------
        $passed = ($allResults | Where-Object { $_.Status -eq 'pass' }).Count
        $failed = ($allResults | Where-Object { $_.Status -eq 'fail' }).Count
        $warnings = ($allResults | Where-Object { $_.Status -eq 'warning' }).Count
        $total = $allResults.Count

        Write-Host ""
        Write-Host "  ----------------------------------------" -ForegroundColor DarkGray
        Write-Host "  Results: $total checks - " -NoNewline
        Write-Host "$passed passed" -ForegroundColor Green -NoNewline
        Write-Host ", $failed failed" -ForegroundColor Red -NoNewline
        Write-Host ", $warnings warnings" -ForegroundColor Yellow
        Write-Host "  ----------------------------------------" -ForegroundColor DarkGray
        Write-Host ""

        # ---------------------------------------------------------------
        # Build JSON payload
        # ---------------------------------------------------------------
        $uploadJson = ConvertTo-UploadJson -CheckResults $allResults.ToArray() -Hostname $hostname
        $json = $uploadJson | ConvertTo-Json -Depth 10

        # ---------------------------------------------------------------
        # Auto-upload to web dashboard
        # ---------------------------------------------------------------
        if ($AutoUpload) {
            Write-Host "  Uploading results to web dashboard..." -ForegroundColor Cyan
            try {
                # Handle self-signed certs for localhost
                $isLocalhost = $AutoUpload -match 'localhost|127\.0\.0\.1'
                $uploadParams = @{
                    Uri         = $AutoUpload
                    Method      = 'POST'
                    Body        = $json
                    ContentType = 'application/json'
                }

                # PowerShell 7+ supports -SkipCertificateCheck
                if ($PSVersionTable.PSVersion.Major -ge 7 -and $isLocalhost) {
                    $uploadParams['SkipCertificateCheck'] = $true
                }
                elseif ($isLocalhost) {
                    # PowerShell 5.1 - bypass cert validation for localhost
                    $certCallback = @"
using System.Net;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
public class TrustAllCerts {
    public static void Ignore() {
        ServicePointManager.ServerCertificateValidationCallback =
            delegate { return true; };
    }
}
"@
                    try {
                        Add-Type $certCallback -ErrorAction SilentlyContinue
                        [TrustAllCerts]::Ignore()
                    }
                    catch {
                        # Type may already be added
                    }
                }

                $response = Invoke-RestMethod @uploadParams
                Write-Host "  [OK] Results uploaded successfully!" -ForegroundColor Green
                if ($response.mergedCount) {
                    Write-Host "  $($response.mergedCount) check(s) merged into assessment." -ForegroundColor Green
                }
                Write-Host ""
            }
            catch {
                Write-Warning "Auto-upload failed: $($_.Exception.Message)"
                Write-Host "  Results will be saved locally as a backup." -ForegroundColor Yellow
                Write-Host ""
            }
        }

        # ---------------------------------------------------------------
        # Save to file (always, as backup or primary output)
        # ---------------------------------------------------------------
        $savePath = $OutputPath
        if (-not $savePath) {
            $savePath = Join-Path (Get-Location) "mtr-results.json"
        }
        $json | Out-File -FilePath $savePath -Encoding utf8 -Force
        Write-Host "  [OK] Results saved to: $savePath" -ForegroundColor Green

        if (-not $AutoUpload) {
            Write-Host ""
            Write-Host "  NEXT STEP:" -ForegroundColor Cyan
            Write-Host "  Go to the web dashboard and click 'Upload PS Results' in the sidebar," -ForegroundColor White
            Write-Host "  or navigate to: http://localhost:3000/upload" -ForegroundColor White
            Write-Host "  Then upload the file: $savePath" -ForegroundColor White
            Write-Host ""
        }

        if ($PassThru) {
            return $allResults.ToArray()
        }
    }
}
